source 'https://rubygems.org'

gem 'rails', '3.2.13'
gem 'unicorn'
gem "active_model_serializers"
gem 'resque', require: "resque/server"
gem 'strong_parameters'

gem 'passenger'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

group :production do
  gem 'pg'
end

group :development do
  gem "better_errors"
  gem "binding_of_caller"
end

group :test, :development do
  gem 'sqlite3'
  gem 'rspec-rails'
  gem 'guard-rspec'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'database_cleaner'
  gem 'debugger'
end