#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

ContactManager::Application.load_tasks

require "resque/tasks"

task "resque:setup" => :environment

desc "Start importing contacts for all users"
task :all_facebook_contact_import => :environment do
  Resque.enqueue(AllFacebookContactImport,{})
end